const crypto = require('crypto');

/**
 * StyleProcessor is responsible for handling all CSS-related logic during the build process.
 * This includes managing global CSS variables, scoping component-specific styles using hashes,
 * and extracting CSS rules into a global stylesheet.
 */
class StyleProcessor {
    /**
     * Creates an instance of StyleProcessor.
     */
    constructor() {
        /** 
         * The accumulated global stylesheet content.
         * @type {string} 
         */
        this.globalStyles = "/* Generated by Avenx-JS (Zero-Classname / @css Tag) */\n";
        
        /** 
         * A map of CSS variable names to their values.
         * @type {Object<string, string>} 
         */
        this.cssVariables = {};
    }

    /**
     * Adds a global CSS variable to the processor.
     * @param {string} name - The name of the variable (without the @ prefix).
     * @param {string} value - The value of the variable.
     */
    addVariable(name, value) {
        this.cssVariables[name] = value;
    }

    /**
     * Retrieves the accumulated global styles.
     * @returns {string} The complete CSS string for the application.
     */
    getGlobalStyles() {
        return this.globalStyles;
    }

    /**
     * Processes the CSS within an HTML template. It identifies <@css> tags,
     * scopes the rules with a unique hash, replaces variables, and updates the HTML
     * to include the hash class.
     * @param {string} html - The HTML template containing <@css> tags.
     * @param {Object} [desBlocks={}] - Pre-defined style blocks from an .axd file.
     * @param {string} [componentName=""] - The name of the component for hash generation.
     * @returns {string} The modified HTML with scoped class names and removed style tags.
     */
    process(html, desBlocks = {}, componentName = "") {
        const cssRegex = /<@css\s*(\w+)?\s*>([\s\S]*?)<\/ @css>|<@css\s*(\w+)?\s*\/?>/g;
        let modifiedHtml = html;
        const matches = [];
        let match;

        while ((match = cssRegex.exec(html)) !== null) {
            matches.push(match);
        }

        let anonymousIndex = 0;
        for (let i = matches.length - 1; i >= 0; i--) {
            const m = matches[i];
            const blockName = m[1] || m[3];
            let cssContent = (m[2] || "").trim();
            const fullMatch = m[0];
            const matchIndex = m.index;

            if (!cssContent) {
                cssContent = blockName ? (desBlocks[blockName] || "") : (desBlocks[`__anon_${anonymousIndex++}`] || "");
            }

            if (!cssContent) {
                modifiedHtml = modifiedHtml.replace(fullMatch, '');
                continue;
            }

            // Replace CSS Variables
            for (const [varName, varValue] of Object.entries(this.cssVariables)) {
                const varRegex = new RegExp(`@${varName}\\b`, 'g');
                cssContent = cssContent.replace(varRegex, varValue);
            }

            const hash = "avenx-" + crypto.createHash('md5').update(cssContent + componentName).digest('hex').substring(0, 8);
            this.extractRules(cssContent, hash);

            const beforeMatch = modifiedHtml.substring(0, matchIndex);
            const lastTagStart = beforeMatch.lastIndexOf('<');
            
            if (lastTagStart !== -1 && beforeMatch[lastTagStart + 1] !== '/') {
                const tagContent = modifiedHtml.substring(lastTagStart, matchIndex);
                let updatedTag;
                if (tagContent.includes('class="')) {
                    updatedTag = tagContent.replace('class="', `class="${hash} `);
                } else {
                    updatedTag = tagContent.replace(/(\s*\/?>)/, ` class="${hash}"$1`);
                }
                
                modifiedHtml = modifiedHtml.substring(0, lastTagStart) + 
                               updatedTag + 
                               modifiedHtml.substring(matchIndex + fullMatch.length);
            } else {
                modifiedHtml = modifiedHtml.replace(fullMatch, '');
            }
        }
        return modifiedHtml;
    }

    /**
     * Extracts CSS rules from a content string, scopes them using the provided hash,
     * and appends them to the global stylesheet. Handles basic nesting with the '&' selector.
     * @param {string} cssContent - The raw CSS string to extract rules from.
     * @param {string} hash - The unique hash to use for scoping.
     * @private
     */
    extractRules(cssContent, hash) {
        let baseRules = "";
        let nestedRules = "";
        let current = "";
        let depth = 0;

        for (let char of cssContent) {
            current += char;
            if (char === '{') depth++;
            else if (char === '}') depth--;
            
            if (depth === 0 && (char === ';' || char === '}')) {
                let rule = current.trim();
                if (rule.includes('{')) {
                    nestedRules += rule.replace(/&/g, `.${hash}`) + "\n";
                } else if (rule && rule !== ';') {
                    if (!rule.endsWith(';')) rule += ';';
                    baseRules += rule + " ";
                }
                current = "";
            }
        }

        if (baseRules.trim()) this.globalStyles += `.${hash} { ${baseRules} }\n`;
        if (nestedRules.trim()) this.globalStyles += nestedRules + "\n";
    }
}

module.exports = StyleProcessor;
